blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/UfpMnqMmEM
    about: Ask and answer questions here.
  - name: Chinese QQ Group
    url: https://qm.qq.com/cgi-bin/qm/qr?k=8EtEpehB1a-nfTNAnngTVqX3o9xoIxmT&jump_from=webapi
    about: Ask and answer questions in Chinese here.
