on:
  workflow_dispatch:
    inputs: {}

jobs:
  release:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
          - runs-on: macos-latest
            arch: osx-x64
          - runs-on: ubuntu-latest
            arch: linux-x64

    steps:
    - uses: actions/checkout@v1

    - name: restore
      run: dotnet restore OpenUtau -r ${{ matrix.os.arch }}

    - name: test
      run: dotnet test OpenUtau.Test
