version: 0.1.{build}
environment:
  access_token:
    secure: VoTH2ml/pRgjLSGhfPO+NZfCoFzFcfrQjEIl/5+0UufeW6mEvccfwvef3gOaD2ke
image:
  - Visual Studio 2022
  - macOS
  - Ubuntu
branches:
  only:
    - master
    - stable
skip_commits:
  files:
    - .github/*
  message: /\[nobuild\]/
skip_tags: true
configuration: Release
dotnet_csproj:
  patch: true
  file: 'OpenUtau\OpenUtau.csproj'
  version: "{version}"
before_build:
  - ps: git config --global credential.helper store
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - ps: git config --global user.email "appveyor@appveyor.com"
  - ps: git config --global user.name "appveyor"
  - cmd: nuget restore
after_test:
  - ps: if ($isWindows) { python appveyor.py 2>&1 } else { python3 appveyor.py 2>&1 }
artifacts:
  - path: bin\win-x86
    name: OpenUtau-win-x86
    type: zip
  - path: bin\win-x64
    name: OpenUtau-win-x64
    type: zip
  - path: OpenUtau-win-x64.exe
  - path: OpenUtau-osx-x64.dmg
  - path: OpenUtau-linux-x64.tar.gz
  - path: appcast.win-x86.xml
  - path: appcast.win-x64.xml
  - path: appcast.win-x64-installer.xml
  - path: appcast.linux-x64.xml
  - path: appcast.osx-x64.xml
  - path: changelog.txt
deploy:
  - provider: GitHub
    tag: build/$(APPVEYOR_BUILD_VERSION)
    release: $(APPVEYOR_BUILD_VERSION) Beta
    description: $(APPVEYOR_BUILD_VERSION) Beta $(APPVEYOR_REPO_COMMIT_TIMESTAMP)
    auth_token:
      secure: VoTH2ml/pRgjLSGhfPO+NZfCoFzFcfrQjEIl/5+0UufeW6mEvccfwvef3gOaD2ke
    draft: false
    prerelease: true
    force_update: true
    on:
      branch: master
      APPVEYOR_REPO_TAG: false
  - provider: GitHub
    tag: build/$(APPVEYOR_BUILD_VERSION)
    release: $(APPVEYOR_BUILD_VERSION)
    description: $(APPVEYOR_BUILD_VERSION) $(APPVEYOR_REPO_COMMIT_TIMESTAMP)
    auth_token:
      secure: VoTH2ml/pRgjLSGhfPO+NZfCoFzFcfrQjEIl/5+0UufeW6mEvccfwvef3gOaD2ke
    draft: false
    prerelease: false
    force_update: true
    on:
      branch: stable
      APPVEYOR_REPO_TAG: false
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:discord_webhook
